-- ============================================================================
-- Bootstrap (run ONCE, manually, as ACCOUNTADMIN).
--
-- schemachange cannot create the role/user/warehouse it itself runs as, nor the
-- change-history table it writes to. This script lays that foundation plus the
-- Firehose ingestion identity, then hands control to schemachange.
--
-- Replace the two RSA_PUBLIC_KEY placeholders with your generated public keys:
--   openssl genrsa 2048 | openssl pkcs8 -topk8 -inform PEM -out rsa_key.p8 -nocrypt
--   openssl rsa -in rsa_key.p8 -pubout -out rsa_key.pub
-- ============================================================================

USE ROLE ACCOUNTADMIN;

-- --- Warehouses -------------------------------------------------------------
CREATE WAREHOUSE IF NOT EXISTS SCHEMACHANGE_WH
WAREHOUSE_SIZE = 'XSMALL' AUTO_SUSPEND = 1 AUTO_RESUME = TRUE INITIALLY_SUSPENDED = TRUE;

CREATE WAREHOUSE IF NOT EXISTS DBT_WH
WAREHOUSE_SIZE = 'XSMALL' AUTO_SUSPEND = 1 AUTO_RESUME = TRUE INITIALLY_SUSPENDED = TRUE;

-- --- schemachange role + user ----------------------------------------------
CREATE ROLE IF NOT EXISTS SCHEMACHANGE_ROLE;

-- Demo scope: let schemachange create databases, roles, users, and warehouses.
-- Production would grant these privileges more narrowly.
GRANT CREATE DATABASE ON ACCOUNT TO ROLE SCHEMACHANGE_ROLE;
GRANT CREATE ROLE ON ACCOUNT TO ROLE SCHEMACHANGE_ROLE WITH GRANT OPTION;
GRANT CREATE USER ON ACCOUNT TO ROLE SCHEMACHANGE_ROLE WITH GRANT OPTION;
GRANT CREATE WAREHOUSE ON ACCOUNT TO ROLE SCHEMACHANGE_ROLE;
GRANT ROLE SCHEMACHANGE_ROLE TO ROLE SYSADMIN;
GRANT USAGE ON WAREHOUSE SCHEMACHANGE_WH TO ROLE SCHEMACHANGE_ROLE;

CREATE USER IF NOT EXISTS SCHEMACHANGE_USER
    DEFAULT_ROLE = SCHEMACHANGE_ROLE
    DEFAULT_WAREHOUSE = SCHEMACHANGE_WH
    RSA_PUBLIC_KEY = 'MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAvZdKJTWINTVPlDny5ABW3I0Zx1ZFH3wmBGJwtSxReFSR/V0DNbq1fJ4tKV2lhZU3sPTSgFVPtfgAOklgx4tdPjkwoQN6NZO9Zt7/fyBbopvCmI4LMxSCv/g7LljPS20oHg1AnF3mJs2mZGmLQI0cxQ/MchvcPM1D4n0R+iqWozMeDgjtaEElDOEPbt6H+nIaMSUv1ss/owfGuDBSJxrq5a654LR/soCP0vUQQ/ii9aoE8bl++DWk7B04pxAt3gWrmIG1/wRAjjQj6wzgKzHq2gmHexlvxMX+/sAY4RbA7vLbC7eCk2R9WZqz4x26IDxY9xlcvBdQQOi3ouG5A0kFfQIDAQAB'  -- noqa: LT05
    COMMENT = 'Runs schemachange deployments';
GRANT ROLE SCHEMACHANGE_ROLE TO USER SCHEMACHANGE_USER;

-- --- Change-history store ---------------------------------------------------
CREATE DATABASE IF NOT EXISTS METADATA;
CREATE SCHEMA IF NOT EXISTS METADATA.SCHEMACHANGE;
GRANT OWNERSHIP ON DATABASE METADATA TO ROLE SCHEMACHANGE_ROLE COPY CURRENT GRANTS;
GRANT OWNERSHIP ON SCHEMA METADATA.SCHEMACHANGE TO ROLE SCHEMACHANGE_ROLE COPY CURRENT GRANTS;

CREATE TABLE IF NOT EXISTS METADATA.SCHEMACHANGE.CHANGE_HISTORY (
    version VARCHAR,
    description VARCHAR,
    script VARCHAR,
    script_type VARCHAR,
    checksum VARCHAR,
    execution_time NUMBER,
    status VARCHAR,
    installed_by VARCHAR,
    installed_on TIMESTAMP_LTZ
);
GRANT OWNERSHIP ON TABLE METADATA.SCHEMACHANGE.CHANGE_HISTORY
TO ROLE SCHEMACHANGE_ROLE COPY CURRENT GRANTS;

-- Database roles on METADATA (same pattern as the medallion DBs in V1.1.2;
-- no NO_PII role since metadata holds no PII). ADMIN is granted to schemachange.
CREATE DATABASE ROLE IF NOT EXISTS METADATA.READ_ONLY;
CREATE DATABASE ROLE IF NOT EXISTS METADATA.READ_WRITE;
CREATE DATABASE ROLE IF NOT EXISTS METADATA.ADMIN;

GRANT USAGE ON DATABASE METADATA TO DATABASE ROLE METADATA.READ_ONLY;
GRANT USAGE ON ALL SCHEMAS IN DATABASE METADATA TO DATABASE ROLE METADATA.READ_ONLY;
GRANT USAGE ON FUTURE SCHEMAS IN DATABASE METADATA TO DATABASE ROLE METADATA.READ_ONLY;
GRANT SELECT ON ALL TABLES IN DATABASE METADATA TO DATABASE ROLE METADATA.READ_ONLY;
GRANT SELECT ON FUTURE TABLES IN DATABASE METADATA TO DATABASE ROLE METADATA.READ_ONLY;

GRANT DATABASE ROLE METADATA.READ_ONLY TO DATABASE ROLE METADATA.READ_WRITE;
GRANT CREATE SCHEMA ON DATABASE METADATA TO DATABASE ROLE METADATA.READ_WRITE;
GRANT INSERT, UPDATE, DELETE ON ALL TABLES IN DATABASE METADATA
TO DATABASE ROLE METADATA.READ_WRITE;
GRANT INSERT, UPDATE, DELETE ON FUTURE TABLES IN DATABASE METADATA
TO DATABASE ROLE METADATA.READ_WRITE;
GRANT CREATE TABLE ON ALL SCHEMAS IN DATABASE METADATA TO DATABASE ROLE METADATA.READ_WRITE;
GRANT CREATE TABLE ON FUTURE SCHEMAS IN DATABASE METADATA TO DATABASE ROLE METADATA.READ_WRITE;

GRANT DATABASE ROLE METADATA.READ_WRITE TO DATABASE ROLE METADATA.ADMIN;
GRANT ALL PRIVILEGES ON DATABASE METADATA TO DATABASE ROLE METADATA.ADMIN;

GRANT DATABASE ROLE METADATA.ADMIN TO ROLE SCHEMACHANGE_ROLE;

-- --- Firehose ingestion identity (must exist before `cdk deploy`) -----------
CREATE ROLE IF NOT EXISTS FIREHOSE_ROLE;
-- Snowpipe Streaming is serverless; warehouse only for ad-hoc checks
GRANT USAGE ON WAREHOUSE SCHEMACHANGE_WH TO ROLE FIREHOSE_ROLE;

CREATE USER IF NOT EXISTS FIREHOSE_USER
    DEFAULT_ROLE = FIREHOSE_ROLE
    RSA_PUBLIC_KEY = 'MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAwFz66FbIlVZsZpL0H1nDCnUPBSBDQuj6XjXZ6uXTapQ06rRVzA9kazDZw4fpCkW+p7jibboCj0Ce2WwuwUwMzpuDs+bm9LnZGbngBs7RQYm94JbVInwmTjj6nNr39c9FTYKS5nNR008chqdm8ltYiGIZNAmJgfVEq+7Bm8+W5Gu1nSRDJ7JUv3C+FhIuXXO2W7sNRIJQqP7t6Ah9Wk2G5HTSTRN3Tibo5IllYaK8nGQtDEdiL699iSseQnT3z6FQ7raz0myAElRfdUKSyfKN7pTSQVm7VGJWaMaZ1kYZ3Fx8I6OCcmV6ERBQNJsiGGb+aS1/UnVYBUaU3ym8ufFdLwIDAQAB'  -- noqa: LT05
    COMMENT = 'Firehose Snowpipe Streaming ingestion user';
GRANT ROLE FIREHOSE_ROLE TO USER FIREHOSE_USER;

-- The landing table and its grants to FIREHOSE_ROLE are created by schemachange
-- (V1.1.6__firehose_landing.sql), which runs after this bootstrap.

-- Allow schemachange to create storage integrations (needed for V1.1.9).
-- CREATE INTEGRATION is an account-level privilege that requires ACCOUNTADMIN.
GRANT CREATE INTEGRATION ON ACCOUNT TO ROLE SCHEMACHANGE_ROLE;

USE ROLE SECURITYADMIN;
GRANT MANAGE GRANTS ON ACCOUNT TO ROLE SCHEMACHANGE_ROLE;
