-- Per-database roles: READ_ONLY, READ_WRITE, ADMIN, NO_PII.
--
-- Database roles are scoped to one database and are granted to account-level
-- roles (e.g. DBT_ROLE). NO_PII mirrors READ_ONLY; it exists so masking policies
-- can branch on "is the caller in <db>.NO_PII?" to hide PII columns.
USE ROLE SCHEMACHANGE_ROLE;

-- Macro-style: same four roles created for each database. Kept explicit so the
-- grants are auditable and lint cleanly.

-- ============================ BRONZE =======================================
CREATE DATABASE ROLE IF NOT EXISTS BRONZE.READ_ONLY;
CREATE DATABASE ROLE IF NOT EXISTS BRONZE.READ_WRITE;
CREATE DATABASE ROLE IF NOT EXISTS BRONZE.ADMIN;
CREATE DATABASE ROLE IF NOT EXISTS BRONZE.NO_PII;

GRANT USAGE ON DATABASE BRONZE TO DATABASE ROLE BRONZE.READ_ONLY;
GRANT USAGE ON ALL SCHEMAS IN DATABASE BRONZE TO DATABASE ROLE BRONZE.READ_ONLY;
GRANT USAGE ON FUTURE SCHEMAS IN DATABASE BRONZE TO DATABASE ROLE BRONZE.READ_ONLY;
GRANT SELECT ON ALL TABLES IN DATABASE BRONZE TO DATABASE ROLE BRONZE.READ_ONLY;
GRANT SELECT ON FUTURE TABLES IN DATABASE BRONZE TO DATABASE ROLE BRONZE.READ_ONLY;
GRANT SELECT ON ALL VIEWS IN DATABASE BRONZE TO DATABASE ROLE BRONZE.READ_ONLY;
GRANT SELECT ON FUTURE VIEWS IN DATABASE BRONZE TO DATABASE ROLE BRONZE.READ_ONLY;

GRANT DATABASE ROLE BRONZE.READ_ONLY TO DATABASE ROLE BRONZE.READ_WRITE;
GRANT CREATE SCHEMA ON DATABASE BRONZE TO DATABASE ROLE BRONZE.READ_WRITE;
GRANT INSERT, UPDATE, DELETE ON ALL TABLES IN DATABASE BRONZE TO DATABASE ROLE BRONZE.READ_WRITE;
GRANT INSERT, UPDATE, DELETE ON FUTURE TABLES IN DATABASE BRONZE TO DATABASE ROLE BRONZE.READ_WRITE;
GRANT CREATE TABLE ON FUTURE SCHEMAS IN DATABASE BRONZE TO DATABASE ROLE BRONZE.READ_WRITE;
GRANT CREATE TABLE ON ALL SCHEMAS IN DATABASE BRONZE TO DATABASE ROLE BRONZE.READ_WRITE;

GRANT DATABASE ROLE BRONZE.READ_WRITE TO DATABASE ROLE BRONZE.ADMIN;
GRANT ALL PRIVILEGES ON DATABASE BRONZE TO DATABASE ROLE BRONZE.ADMIN;

GRANT DATABASE ROLE BRONZE.READ_ONLY TO DATABASE ROLE BRONZE.NO_PII;

-- ============================ SILVER =======================================
CREATE DATABASE ROLE IF NOT EXISTS SILVER.READ_ONLY;
CREATE DATABASE ROLE IF NOT EXISTS SILVER.READ_WRITE;
CREATE DATABASE ROLE IF NOT EXISTS SILVER.ADMIN;
CREATE DATABASE ROLE IF NOT EXISTS SILVER.NO_PII;

GRANT USAGE ON DATABASE SILVER TO DATABASE ROLE SILVER.READ_ONLY;
GRANT USAGE ON ALL SCHEMAS IN DATABASE SILVER TO DATABASE ROLE SILVER.READ_ONLY;
GRANT USAGE ON FUTURE SCHEMAS IN DATABASE SILVER TO DATABASE ROLE SILVER.READ_ONLY;
GRANT SELECT ON ALL TABLES IN DATABASE SILVER TO DATABASE ROLE SILVER.READ_ONLY;
GRANT SELECT ON FUTURE TABLES IN DATABASE SILVER TO DATABASE ROLE SILVER.READ_ONLY;
GRANT SELECT ON ALL VIEWS IN DATABASE SILVER TO DATABASE ROLE SILVER.READ_ONLY;
GRANT SELECT ON FUTURE VIEWS IN DATABASE SILVER TO DATABASE ROLE SILVER.READ_ONLY;

GRANT DATABASE ROLE SILVER.READ_ONLY TO DATABASE ROLE SILVER.READ_WRITE;
GRANT CREATE SCHEMA ON DATABASE SILVER TO DATABASE ROLE SILVER.READ_WRITE;
GRANT INSERT, UPDATE, DELETE ON ALL TABLES IN DATABASE SILVER TO DATABASE ROLE SILVER.READ_WRITE;
GRANT INSERT, UPDATE, DELETE ON FUTURE TABLES IN DATABASE SILVER TO DATABASE ROLE SILVER.READ_WRITE;
GRANT CREATE TABLE ON FUTURE SCHEMAS IN DATABASE SILVER TO DATABASE ROLE SILVER.READ_WRITE;
GRANT CREATE TABLE ON ALL SCHEMAS IN DATABASE SILVER TO DATABASE ROLE SILVER.READ_WRITE;

GRANT DATABASE ROLE SILVER.READ_WRITE TO DATABASE ROLE SILVER.ADMIN;
GRANT ALL PRIVILEGES ON DATABASE SILVER TO DATABASE ROLE SILVER.ADMIN;

GRANT DATABASE ROLE SILVER.READ_ONLY TO DATABASE ROLE SILVER.NO_PII;

-- ============================ GOLD =========================================
CREATE DATABASE ROLE IF NOT EXISTS GOLD.READ_ONLY;
CREATE DATABASE ROLE IF NOT EXISTS GOLD.READ_WRITE;
CREATE DATABASE ROLE IF NOT EXISTS GOLD.ADMIN;
CREATE DATABASE ROLE IF NOT EXISTS GOLD.NO_PII;

GRANT USAGE ON DATABASE GOLD TO DATABASE ROLE GOLD.READ_ONLY;
GRANT USAGE ON ALL SCHEMAS IN DATABASE GOLD TO DATABASE ROLE GOLD.READ_ONLY;
GRANT USAGE ON FUTURE SCHEMAS IN DATABASE GOLD TO DATABASE ROLE GOLD.READ_ONLY;
GRANT SELECT ON ALL TABLES IN DATABASE GOLD TO DATABASE ROLE GOLD.READ_ONLY;
GRANT SELECT ON FUTURE TABLES IN DATABASE GOLD TO DATABASE ROLE GOLD.READ_ONLY;
GRANT SELECT ON ALL VIEWS IN DATABASE GOLD TO DATABASE ROLE GOLD.READ_ONLY;
GRANT SELECT ON FUTURE VIEWS IN DATABASE GOLD TO DATABASE ROLE GOLD.READ_ONLY;

GRANT DATABASE ROLE GOLD.READ_ONLY TO DATABASE ROLE GOLD.READ_WRITE;
GRANT CREATE SCHEMA ON DATABASE GOLD TO DATABASE ROLE GOLD.READ_WRITE;
GRANT INSERT, UPDATE, DELETE ON ALL TABLES IN DATABASE GOLD TO DATABASE ROLE GOLD.READ_WRITE;
GRANT INSERT, UPDATE, DELETE ON FUTURE TABLES IN DATABASE GOLD TO DATABASE ROLE GOLD.READ_WRITE;
GRANT CREATE TABLE ON FUTURE SCHEMAS IN DATABASE GOLD TO DATABASE ROLE GOLD.READ_WRITE;
GRANT CREATE TABLE ON ALL SCHEMAS IN DATABASE GOLD TO DATABASE ROLE GOLD.READ_WRITE;
GRANT CREATE VIEW ON ALL SCHEMAS IN DATABASE GOLD TO DATABASE ROLE GOLD.READ_WRITE;
GRANT CREATE VIEW ON FUTURE SCHEMAS IN DATABASE GOLD TO DATABASE ROLE GOLD.READ_WRITE;

GRANT DATABASE ROLE GOLD.READ_WRITE TO DATABASE ROLE GOLD.ADMIN;
GRANT ALL PRIVILEGES ON DATABASE GOLD TO DATABASE ROLE GOLD.ADMIN;

GRANT DATABASE ROLE GOLD.READ_ONLY TO DATABASE ROLE GOLD.NO_PII;

-- ============================ GOVERNANCE ===================================
CREATE DATABASE ROLE IF NOT EXISTS GOVERNANCE.READ_ONLY;
CREATE DATABASE ROLE IF NOT EXISTS GOVERNANCE.READ_WRITE;
CREATE DATABASE ROLE IF NOT EXISTS GOVERNANCE.ADMIN;
CREATE DATABASE ROLE IF NOT EXISTS GOVERNANCE.NO_PII;

GRANT USAGE ON DATABASE GOVERNANCE TO DATABASE ROLE GOVERNANCE.READ_ONLY;
GRANT USAGE ON ALL SCHEMAS IN DATABASE GOVERNANCE TO DATABASE ROLE GOVERNANCE.READ_ONLY;
GRANT USAGE ON FUTURE SCHEMAS IN DATABASE GOVERNANCE TO DATABASE ROLE GOVERNANCE.READ_ONLY;
GRANT SELECT ON ALL TABLES IN DATABASE GOVERNANCE TO DATABASE ROLE GOVERNANCE.READ_ONLY;
GRANT SELECT ON FUTURE TABLES IN DATABASE GOVERNANCE TO DATABASE ROLE GOVERNANCE.READ_ONLY;

GRANT DATABASE ROLE GOVERNANCE.READ_ONLY TO DATABASE ROLE GOVERNANCE.READ_WRITE;
GRANT INSERT, UPDATE, DELETE ON ALL TABLES IN DATABASE GOVERNANCE
TO DATABASE ROLE GOVERNANCE.READ_WRITE;
GRANT INSERT, UPDATE, DELETE ON FUTURE TABLES IN DATABASE GOVERNANCE
TO DATABASE ROLE GOVERNANCE.READ_WRITE;

GRANT DATABASE ROLE GOVERNANCE.READ_WRITE TO DATABASE ROLE GOVERNANCE.ADMIN;
GRANT ALL PRIVILEGES ON DATABASE GOVERNANCE TO DATABASE ROLE GOVERNANCE.ADMIN;

GRANT DATABASE ROLE GOVERNANCE.READ_ONLY TO DATABASE ROLE GOVERNANCE.NO_PII;
