-- Grant DBT_ROLE the APPLY privilege on all per-resource governance policies
-- so that dbt post-hooks can attach them to secured views.
--
-- APPLY on a masking / row access policy is the Snowflake privilege that allows
-- a role to SET / UNSET that policy on a column or table — distinct from the
-- CREATE privilege (which lets you define the policy itself, held by SCHEMACHANGE_ROLE).
USE ROLE SCHEMACHANGE_ROLE;

-- ── Masking policies ───────────────────────────────────────────────────────
GRANT APPLY ON MASKING POLICY GOVERNANCE.SECURITY.MASK_CUSTOMER_PII_STRING TO ROLE DBT_ROLE;
GRANT APPLY ON MASKING POLICY GOVERNANCE.SECURITY.MASK_CUSTOMER_FINANCIAL_NUMBER TO ROLE DBT_ROLE;
GRANT APPLY ON MASKING POLICY GOVERNANCE.SECURITY.MASK_PRODUCT_FINANCIAL_NUMBER TO ROLE DBT_ROLE;
GRANT APPLY ON MASKING POLICY GOVERNANCE.SECURITY.MASK_ORDER_FINANCIAL_NUMBER TO ROLE DBT_ROLE;
GRANT APPLY ON MASKING POLICY GOVERNANCE.SECURITY.MASK_ORDER_ITEM_FINANCIAL_NUMBER TO ROLE DBT_ROLE;
GRANT APPLY ON MASKING POLICY GOVERNANCE.SECURITY.MASK_PAYMENT_PII_STRING TO ROLE DBT_ROLE;
GRANT APPLY ON MASKING POLICY GOVERNANCE.SECURITY.MASK_PAYMENT_FINANCIAL_NUMBER TO ROLE DBT_ROLE;

-- ── Row access policies ────────────────────────────────────────────────────
GRANT APPLY ON ROW ACCESS POLICY GOVERNANCE.SECURITY.RAP_CUSTOMER TO ROLE DBT_ROLE;
GRANT APPLY ON ROW ACCESS POLICY GOVERNANCE.SECURITY.RAP_STORE TO ROLE DBT_ROLE;
GRANT APPLY ON ROW ACCESS POLICY GOVERNANCE.SECURITY.RAP_PRODUCT TO ROLE DBT_ROLE;
GRANT APPLY ON ROW ACCESS POLICY GOVERNANCE.SECURITY.RAP_ORDER TO ROLE DBT_ROLE;
GRANT APPLY ON ROW ACCESS POLICY GOVERNANCE.SECURITY.RAP_ORDER_ITEM TO ROLE DBT_ROLE;
GRANT APPLY ON ROW ACCESS POLICY GOVERNANCE.SECURITY.RAP_PAYMENT TO ROLE DBT_ROLE;
